### ISSUE TITLE
InfluxDB2 config.ini parameters

### ISSUE THREAD

**Issue by zarianu** [wifinigel/wiperf_poller#1]
Hello there!

I've found some typos in helpers/config.py: _influx_host2_ and _influx_port2_ vs. _influx2_host_ and _influx2_port_ parameters in config.ini.

And here's little feature request - pls add .ini parameter for InfluxDB transport select (HTTP or HTTPS), this could be useful.

Sorry, I don't have python dev environment right now so I coudn't submit pull requests (monkey-patched code right on my WLANPi), maybe later.

Thanks for your great efforts creating this useful tool.

Regards,
Konstantin

**Comment by wifinigel** [comment]
Thanks Konstantin,

I'll get those fixed up and will add the transport selection to the roadmap. Thanks!

Nigel.

**Comment by wifinigel** [comment]
Fix added to config.ini in v2.1 build
