### ISSUE TITLE
Quick question :)

### ISSUE THREAD

**Issue by wifinigel** [wifinigel/wiperf_poller#11]
The HTTP_test also supports IPv6 version? How can we force ipv6 HTTP test?

Óscar Leal

**Comment by wifinigel** [comment]
Several fields were missed from the new config.ini file. these have been added and new config.ini file pushed.

Fields now:

```
; First HTTP target
; target URL
http_target_1: https://google.com
; select IPv4/IPv6 (IPv4 if no arg provided)
http_target_1: ipv4
; additonal commands to pass to curl (advanced option)
http_target_curl_args_1: 

;
; Second HTTP target
http_target_2: https://cisco.com
http_target_2: ipv4
http_target_curl_args_2: 
```

**Comment by lealog** [comment]
@wifinigel , you have "http_target_x" duplicated and this is causing and error.

**Comment by lealog** [comment]
tested and it's OK
