### ISSUE TITLE
Error - Configuring WLANPI with version V3

### ISSUE THREAD

**Issue by lealog** [wifinigel/wiperf_poller#22]
Using WLANPI and installing the version V3, I'm get the following errors:

> root@wlanpi:/home/wlanpi# /usr/bin/python3 /usr/share/wiperf/wiperf_run.py
> Traceback (most recent call last):
>   File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
>     agent.run()
>   File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 480, in run
>     main()
>   File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 350, in main
>     test_result = iperf3_tcp_obj.run_tcp_test(config_vars, status_file_obj, check_correct_mode_interface, exporter_obj)
>   File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/iperf3tester.py", line 114, in run_tcp_test
>     duration = int(config_vars['iperf3_tcp_duration'])
> ValueError: invalid literal for int() with base 10: ''

The wiperf log:

> 2021-03-23 00:51:01,649 - Probe_Log - INFO - ########## iperf3 tcp test ##########
> 2021-03-23 00:56:06,195 - Probe_Log - INFO - *****************************************************
> 2021-03-23 00:56:06,196 - Probe_Log - INFO -  Starting logging...
> 2021-03-23 00:56:06,197 - Probe_Log - INFO - *****************************************************
> 2021-03-23 00:56:06,229 - Probe_Log - INFO - (Note: logging set to debug level.)
> 2021-03-23 00:56:06,231 - Probe_Log - INFO - Checking optional OS commands are available.
> 2021-03-23 00:56:06,231 - Probe_Log - WARNING - Unable to find optional OS command: SMB_MOUNT (Some functionality may not be available)
> 2021-03-23 00:56:06,232 - Probe_Log - WARNING - Unable to find optional OS command: LIBRESPEED_CMD (Some functionality may not be available)
> 2021-03-23 00:56:06,233 - Probe_Log - INFO - Checking required OS commands are available.
> 2021-03-23 00:56:06,234 - Probe_Log - DEBUG - #### Initialized WirelessAdapter instance... ####
> 2021-03-23 00:56:06,235 - Probe_Log - INFO - Checking if we use remote cfg file...
> 2021-03-23 00:56:06,236 - Probe_Log - INFO - No remote cfg file confgured...using current local ini file.
> 2021-03-23 00:56:06,237 - Probe_Log - INFO - No lock file found. Creating lock file.
> 2021-03-23 00:56:06,239 - Probe_Log - INFO - ########## Network connection checks ##########
> 
> 
> 
> 
> 
> 
> 2021-03-23 00:56:07,242 - Probe_Log - INFO - Checking wireless connection is good...(layer 1 &2)
> 2021-03-23 00:56:07,243 - Probe_Log - DEBUG - #### Initialized WirelessAdapter instance... ####
> 2021-03-23 00:56:07,244 - Probe_Log - INFO -   Checking wireless connection available.
> 2021-03-23 00:56:07,245 - Probe_Log - DEBUG - Getting wireless adapter info...
> 2021-03-23 00:56:07,273 - Probe_Log - DEBUG - Wireless interface config info: wlan0     IEEE 802.11  ESSID:"rede_wifi_internal_:D"
>           Mode:Managed  Frequency:5.18 GHz  Access Point: 00:60:6B:50:01:0C
>           Bit Rate=866.7 Mb/s   Tx-Power=20 dBm
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:off
>           Link Quality=70/70  Signal level=-31 dBm
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:1  Invalid misc:3   Missed beacon:0
> 
> 
> 2021-03-23 00:56:07,276 - Probe_Log - DEBUG - ssid = rede_wifi_internal_:D
> 2021-03-23 00:56:07,279 - Probe_Log - DEBUG - bssid = 00:60:6B:50:01:0C
> 2021-03-23 00:56:07,282 - Probe_Log - DEBUG - freq = 5.18
> 
> 2021-03-23 00:56:07,285 - Probe_Log - DEBUG - tx_bit_rate = 866.7
> 2021-03-23 00:56:07,288 - Probe_Log - DEBUG - signal_level = -31
> 2021-03-23 00:56:07,291 - Probe_Log - DEBUG - tx_retries = 1
> 2021-03-23 00:56:07,329 - Probe_Log - DEBUG - Wireless interface config info (iw dev wlanX info): Interface wlan0
>         ifindex 4
>         wdev 0x1
>         addr 8c:88:2d:00:23:7d
>         ssid rede_wifi_internal_:D
>         type managed
>         wiphy 0
>         channel 36 (5180 MHz), width: 80 MHz, center1: 5210 MHz
>         txpower 20.00 dBm
>         multicast TXQ:
>                 qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
>                 0       0       0       0       0       0       0       0               0
> 
> 2021-03-23 00:56:07,333 - Probe_Log - DEBUG - channel_width = 80
> 
> 2021-03-23 00:56:07,335 - Probe_Log - DEBUG - center_freq = 5210
> 2021-03-23 00:56:07,358 - Probe_Log - DEBUG - Wireless interface config info (iw dev wlanX link): Connected to 00:60:6b:50:01:0c (on wlan0)
>         SSID: rede_wifi_internal_:D
>         freq: 5180
>         RX: 2141014 bytes (8820 packets)
>         TX: 311099 bytes (1678 packets)
>         signal: -31 dBm
>         rx bitrate: 866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
>         tx bitrate: 866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
> 
>         bss flags:      short-slot-time
>         dtim period:    1
>         beacon int:     100
> 
> 
> 2021-03-23 00:56:07,383 - Probe_Log - DEBUG - Wireless interface config info (iw dev wlanX station dump): Station 00:60:6b:50:01:0c (on wlan0)
>         inactive time:  468 ms
>         rx bytes:       2141014
>         rx packets:     8820
>         tx bytes:       311099
>         tx packets:     1678
>         tx retries:     83
>         tx failed:      1
>         beacon loss:    0
>         beacon rx:      3677
>         rx drop misc:   3
>         signal:         -31 [-35, -31] dBm
>         signal avg:     -30 [-34, -30] dBm
>         beacon signal avg:      -31 dBm
>         tx bitrate:     866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
>         tx duration:    34831 us
>         rx bitrate:     866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
>         rx duration:    15322 us
>         airtime weight: 256
>         expected throughput:    370.971Mbps
>         authorized:     yes
>         authenticated:  yes
>         associated:     yes
>         preamble:       long
>         WMM/WME:        yes
>         MFP:            no
>         TDLS peer:      no
>         DTIM period:    1
>         beacon interval:100
>         short slot time:yes
>         connected time: 378 seconds
>         associated at [boottime]:       249.359s
>         associated at:  1616460590542 ms
>         current time:   1616460967380 ms
> 
> 2021-03-23 00:56:07,387 - Probe_Log - DEBUG - rx_bit_rate = 866.7
> 2021-03-23 00:56:07,389 - Probe_Log - DEBUG - tx_mcs = 9
> 2021-03-23 00:56:07,392 - Probe_Log - DEBUG - rx_mcs = 9
> 2021-03-23 00:56:07,393 - Probe_Log - DEBUG - Results list: ['rede_wifi_internal_:D', '00:60:6B:50:01:0C', 5.18, 866.7, -31.0, 1, 36]
> 2021-03-23 00:56:07,394 - Probe_Log - INFO - Checking we're connected to the network (layer3)
> 2021-03-23 00:56:07,395 - Probe_Log - INFO -   Checking we have an IP address.
> 2021-03-23 00:56:07,423 - Probe_Log - DEBUG - Interface config info: wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.1.104  netmask 255.255.255.0  broadcast 192.168.1.255
>         inet6 fe80::8e88:2dff:fe00:237d  prefixlen 64  scopeid 0x20<link>
>         inet6 xxxxxxxxxxxxxxxxxx  prefixlen 64  scopeid 0x0<global>
>         ether 8c:88:2d:00:23:7d  txqueuelen 1000  (Ethernet)
>         RX packets 2725  bytes 452989 (442.3 KiB)
>         RX errors 0  dropped 1  overruns 0  frame 0
>         TX packets 2331  bytes 410065 (400.4 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> 
> 2021-03-23 00:56:07,428 - Probe_Log - DEBUG - IP Address = 192.168.1.104
> 2021-03-23 00:56:07,429 - Probe_Log - INFO -   Checking we can do a DNS lookup to ipv4.google.com
> 2021-03-23 00:56:07,430 - Probe_Log - DEBUG - Pinging host: ipv4.google.com (count=1)
> 2021-03-23 00:56:07,531 - Probe_Log - DEBUG - Ping command output:
> 2021-03-23 00:56:07,533 - Probe_Log - DEBUG - ['PING ipv4.l.google.com (142.250.200.142) 56(84) bytes of data.', '', '--- ipv4.l.google.com ping statistics ---', '1 packets transmitted, 1 received, 0% packet loss, time 0ms', 'rtt min/avg/max/mdev = 18.310/18.310/18.310/0.000 ms']
> 2021-03-23 00:56:07,538 - Probe_Log - DEBUG - Packets transmitted: 1
> 2021-03-23 00:56:07,539 - Probe_Log - DEBUG - Packets received: 1
> 2021-03-23 00:56:07,540 - Probe_Log - DEBUG - Packet loss(%): 0
> 2021-03-23 00:56:07,541 - Probe_Log - DEBUG - Test duration (mS): 0
> 2021-03-23 00:56:07,544 - Probe_Log - DEBUG - rtt_min : 18.310
> 2021-03-23 00:56:07,545 - Probe_Log - DEBUG - rtt_avg : 18.310
> 2021-03-23 00:56:07,546 - Probe_Log - DEBUG - rtt_max : 18.310
> 2021-03-23 00:56:07,547 - Probe_Log - DEBUG - rtt_mdev : 0.000
> 2021-03-23 00:56:07,548 - Probe_Log - INFO - ping_host: ipv4.google.com, pkts_tx: 1, pkts_rx: 1, pkt_loss: 0, rtt_avg: 18.310
> 2021-03-23 00:56:07,584 - Probe_Log - INFO -   Checked interface route to : 142.250.200.142. Result: 142.250.200.142 via 192.168.1.1 dev wlan0 src 192.168.1.104 uid 0
> 2021-03-23 00:56:07,585 - Probe_Log - INFO - Checking we can get to the management platform (host = 192.168.192.104, port = 8086, type = influxdb)
> 2021-03-23 00:56:07,586 - Probe_Log - INFO -   Checking we will send mgt traffic over configured interface 'ztukutsbw2' mode.
> 2021-03-23 00:56:07,610 - Probe_Log - INFO -   Checked interface route to : 192.168.192.104. Result: 192.168.192.104 dev ztukutsbw2 src 192.168.192.84 uid 0
> 2021-03-23 00:56:07,612 - Probe_Log - INFO -   Mgt interface route looks good.
> 2021-03-23 00:56:07,613 - Probe_Log - INFO -   Checking port connection to InfluxDB server 192.168.192.104, port: 8086
> 2021-03-23 00:56:07,690 - Probe_Log - INFO -   Port connection to server 192.168.192.104, port: 8086 checked OK.
> 2021-03-23 00:56:07,691 - Probe_Log - INFO - ########## Wireless Connection ##########
> 2021-03-23 00:56:07,692 - Probe_Log - INFO - Wireless connection data: SSID:rede_wifi_internal_:D, BSSID:00:60:6B:50:01:0C, Freq:5.18, Center Freq:5.21, Channel: 36, Channel Width: 80, Tx Phy rate:866.7,             Rx Phy rate:866.7, Tx MCS: 9, Rx MCS: 9, RSSI:-31.0, Tx retries:1, IP address:192.168.1.104
> 2021-03-23 00:56:07,693 - Probe_Log - INFO - Sending results to local file cache.
> 2021-03-23 00:56:07,699 - Probe_Log - INFO - InfluxDB update: wiperf-network, source=Network Tests
> 2021-03-23 00:56:07,700 - Probe_Log - INFO - Sending results data to Influx host: 192.168.192.104, port: 8086, database: wiperf)
> 2021-03-23 00:56:07,704 - Probe_Log - DEBUG - Creating InfluxDB API client...
> 2021-03-23 00:56:07,705 - Probe_Log - DEBUG - Remote host: -192.168.192.104-
> 2021-03-23 00:56:07,706 - Probe_Log - DEBUG - Port: -8086-
> 2021-03-23 00:56:07,707 - Probe_Log - DEBUG - Database: -wiperf-
> 2021-03-23 00:56:07,707 - Probe_Log - DEBUG - User: -wiperf_probe-
> 2021-03-23 00:56:08,451 - Probe_Log - INFO - Data sent to influx OK
> 2021-03-23 00:56:08,454 - Probe_Log - DEBUG - Data structure sent to Influx:
> 2021-03-23 00:56:08,455 - Probe_Log - DEBUG - {'measurement': 'wiperf-network', 'tags': {'host': 'wlanpi'}, 'fields': {'time': 1616460967691, 'ssid': 'rede_wifi_internal_:D', 'bssid': '00:60:6B:50:01:0C', 'freq_ghz': 5.18, 'center_freq_ghz': 5.21, 'channel': 36, 'channel_width': 80, 'tx_rate_mbps': 866.7, 'rx_rate_mbps': 866.7, 'tx_mcs': 9, 'rx_mcs': 9, 'signal_level_dbm': -31.0, 'tx_retries': 1, 'ip_address': '192.168.1.104', 'location': 'wlanpi_redewifi_internal_5G'}, 'time': 1616460967691}
> 2021-03-23 00:56:08,456 - Probe_Log - INFO - Connection results sent OK.
> 2021-03-23 00:56:08,479 - Probe_Log - DEBUG - Interface config info: wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.1.104  netmask 255.255.255.0  broadcast 192.168.1.255
>         inet6 fe80::8e88:2dff:fe00:237d  prefixlen 64  scopeid 0x20<link>
>         inet6 xxxxxxxxxxxxxxxxxx  prefixlen 64  scopeid 0x0<global>
>         ether 8c:88:2d:00:23:7d  txqueuelen 1000  (Ethernet)
>         RX packets 2730  bytes 454156 (443.5 KiB)
>         RX errors 0  dropped 1  overruns 0  frame 0
>         TX packets 2346  bytes 412991 (403.3 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> 
> 2021-03-23 00:56:08,480 - Probe_Log - DEBUG - IP Address = 192.168.1.104
> 2021-03-23 00:56:08,481 - Probe_Log - INFO - ######## spooler checks ########
> 2021-03-23 00:56:08,482 - Probe_Log - INFO - Checking for files to prune.
> 2021-03-23 00:56:08,486 - Probe_Log - INFO - Spool dir does not exist yet.
> 2021-03-23 00:56:08,487 - Probe_Log - INFO - ########## speedtest ##########
> 2021-03-23 00:56:08,488 - Probe_Log - INFO - Starting speedtest (ookla)...
> 2021-03-23 00:56:09,514 - Probe_Log - INFO -   Checked interface route to : 8.8.8.8. Result: 8.8.8.8 via 192.168.1.1 dev wlan0 src 192.168.1.104 uid 0
> 2021-03-23 00:56:09,515 - Probe_Log - INFO - Speedtest in progress....please wait.
> 2021-03-23 00:56:09,516 - Probe_Log - DEBUG - Running Ookla speedtest.
> 2021-03-23 00:57:00,829 - Probe_Log - INFO - time: 1616461020828, ping_time: 10, download_rate_mbps: 306.08, upload_rate_mbps: 84.33, server_name: speedtest.ptservidor.pt:8080, mbytes_sent: 105.68,  mbytes_received: 382.99, latency_ms: 10, jitter_ms: None, client_ip: xxxxxxx, provider: Ookla
> 2021-03-23 00:57:00,831 - Probe_Log - DEBUG - Main: Speedtest results:
> 2021-03-23 00:57:00,833 - Probe_Log - DEBUG - {'time': 1616461020828, 'ping_time': 10, 'download_rate_mbps': 306.08, 'upload_rate_mbps': 84.33, 'server_name': 'speedtest.ptservidor.pt:8080', 'mbytes_sent': 105.68, 'mbytes_received': 382.99, 'latency_ms': 10, 'jitter_ms': None, 'client_ip': 'xxxxxxx', 'provider': 'Ookla'}
> 2021-03-23 00:57:00,833 - Probe_Log - INFO - Speedtest ended.
> 2021-03-23 00:57:00,834 - Probe_Log - INFO - Sending results to local file cache.
> 2021-03-23 00:57:00,839 - Probe_Log - INFO - InfluxDB update: wiperf-speedtest, source=Speedtest
> 2021-03-23 00:57:00,841 - Probe_Log - INFO - Sending results data to Influx host: 192.168.192.104, port: 8086, database: wiperf)
> 2021-03-23 00:57:00,844 - Probe_Log - DEBUG - Creating InfluxDB API client...
> 2021-03-23 00:57:00,845 - Probe_Log - DEBUG - Remote host: -192.168.192.104-
> 2021-03-23 00:57:00,846 - Probe_Log - DEBUG - Port: -8086-
> 2021-03-23 00:57:00,847 - Probe_Log - DEBUG - Database: -wiperf-
> 2021-03-23 00:57:00,847 - Probe_Log - DEBUG - User: -wiperf_probe-
> 2021-03-23 00:57:01,473 - Probe_Log - INFO - Data sent to influx OK
> 2021-03-23 00:57:01,476 - Probe_Log - DEBUG - Data structure sent to Influx:
> 2021-03-23 00:57:01,477 - Probe_Log - DEBUG - {'measurement': 'wiperf-speedtest', 'tags': {'host': 'wlanpi'}, 'fields': {'time': 1616461020828, 'ping_time': 10, 'download_rate_mbps': 306.08, 'upload_rate_mbps': 84.33, 'server_name': 'speedtest.ptservidor.pt:8080', 'mbytes_sent': 105.68, 'mbytes_received': 382.99, 'latency_ms': 10, 'jitter_ms': None, 'client_ip': 'xxxxxxx', 'provider': 'Ookla'}, 'time': 1616461020828}
> 2021-03-23 00:57:01,478 - Probe_Log - INFO - Speedtest results sent OK.
> 2021-03-23 00:57:01,479 - Probe_Log - INFO - ########## ping tests ##########
> 2021-03-23 00:57:01,480 - Probe_Log - INFO - Starting ping test...
> 2021-03-23 00:57:02,483 - Probe_Log - INFO - ########## dns tests ##########
> 2021-03-23 00:57:02,484 - Probe_Log - INFO - Starting DNS tests...
> 2021-03-23 00:57:03,487 - Probe_Log - INFO - ########## http tests ##########
> 2021-03-23 00:57:03,488 - Probe_Log - INFO - Starting HTTP tests...
> 2021-03-23 00:57:04,491 - Probe_Log - ERROR - Looks like quite a few http tests failed, incrementing watchdog.
> 2021-03-23 00:57:04,493 - Probe_Log - INFO - ########## iperf3 tcp test ##########
> 

Do you have any idea why this is happening?

**Comment by wifinigel** [comment]
Oscar, the line numbers reported as failing look like an old version of the wiperf code. Also, speedtest tests were moved to the end of the test cycle in v3, not at the start as shown in the log files. I'm not sure you have the v3 code installed.

Try the following:

1.  Put the wlanpi in to classic mode

2. Uninstall the wiperf code:

    `curl -s https://raw.githubusercontent.com/wifinigel/wiperf/main/setup.sh | sudo bash -s remove wlanpi`

3. Install the new v3 dev code:
    
    `curl -s https://raw.githubusercontent.com/wifinigel/wiperf/dev/setup.sh | sudo bash -s install wlanpi dev`

4. Copy the config.ini template file to become your live config file:

    `sudo cp /etc/wiperf/config.default.ini /etc/wiperf/config.ini`

5. Edit the config.ini file for your env:

    `sudo nano /etc/wiperf/config.ini`

6. Edit the wiperf wpa_supplicant file:

    `sudo nano /etc/wiperf/conf/etc/wpa_supplicant/wpa_supplicant.conf`

7. Switch to wiperf mode

**Comment by lealog** [comment]
Hi Nigel,

Thanks for the feedback.
I have now the wlanpi working as expected after follow your steps.

My previous steps were:
curl -s https://raw.githubusercontent.com/wifinigel/wiperf/main/setup.sh | sudo bash -s remove wlanpi
curl -s https://raw.githubusercontent.com/wifinigel/wiperf/dev/setup.sh | sudo bash -s install wlanpi dev

But I didn't apply these commands in "classic mode". Probably this was the initial issue.

Can be closed.

Thanks again.
