### ISSUE TITLE
IPv6 - Issue looking up route (route cmd syntax?)

### ISSUE THREAD

**Issue by lealog** [wifinigel/wiperf_poller#24]
Using the latest V3 version, I'm having the following error when IPv6 is enabled. 

> ERROR -   [Check Interface Routes (IPv6)] Issue looking up route (route cmd syntax?): Error: inet6 prefix is expected rather than "192.168.1.165".

Scenario:
- wlanpi or rpi4
- Connected only via Wi-Fi
- No ethernet port connected

Please check below the log:

> 2021-03-26 20:52:05,185 - Probe_Log - INFO - ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
> 2021-03-26 20:52:05,186 - Probe_Log - INFO - Network testing connection IPV6 tests (wlan0)
> 2021-03-26 20:52:05,186 - Probe_Log - INFO - ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
> 2021-03-26 20:52:05,186 - Probe_Log - INFO -   Checking if we have an IPv6 address (wlan0)
> 2021-03-26 20:52:05,186 - Probe_Log - INFO -   Getting adapter IPv6 info: wlan0
> 2021-03-26 20:52:05,198 - Probe_Log - DEBUG - Interface config info:     inet6 2001xxxxxxxxxxxxxxxxxxxxx:2006/64 scope global dynamic mngtmpaddr
> 
> 2021-03-26 20:52:05,199 - Probe_Log - DEBUG - IP Address = 2001xxxxxxxxxxxxxxxxxxxxx:2006
> 2021-03-26 20:52:05,199 - Probe_Log - INFO -   Checking we can do an ipv6 DNS lookup to ipv6.google.com
> 2021-03-26 20:52:05,199 - Probe_Log - DEBUG - Pinging host: ipv6.google.com (count=1)
> 2021-03-26 20:52:05,293 - Probe_Log - DEBUG - Ping command output:
> 2021-03-26 20:52:05,293 - Probe_Log - DEBUG - ['PING ipv6.google.com(mad06s10-in-x0e.1e100.net (2a00:1450:4003:808::200e)) 56 data bytes', '', '--- ipv6.google.com ping statistics ---', '1 packets transmitted, 1 received, 0% packet loss, time 0ms', 'rtt min/avg/max/mdev = 18.366/18.366/18.366/0.000 ms']
> 2021-03-26 20:52:05,294 - Probe_Log - DEBUG - Packets transmitted: 1
> 2021-03-26 20:52:05,294 - Probe_Log - DEBUG - Packets received: 1
> 2021-03-26 20:52:05,294 - Probe_Log - DEBUG - Packet loss(%): 0
> 2021-03-26 20:52:05,294 - Probe_Log - DEBUG - Test duration (mS): 0
> 2021-03-26 20:52:05,295 - Probe_Log - DEBUG - rtt_min : 18.366
> 2021-03-26 20:52:05,295 - Probe_Log - DEBUG - rtt_avg : 18.366
> 2021-03-26 20:52:05,295 - Probe_Log - DEBUG - rtt_max : 18.366
> 2021-03-26 20:52:05,295 - Probe_Log - DEBUG - rtt_mdev : 0.000
> 2021-03-26 20:52:05,295 - Probe_Log - INFO -   ping_host: ipv6.google.com, pkts_tx: 1, pkts_rx: 1, pkt_loss: 0, rtt_avg: 18.366
> 2021-03-26 20:52:05,300 - Probe_Log - INFO -   DNS hostname lookup : ipv6.google.com / Result: 2a00:1450:4003:808::200e
> 2021-03-26 20:52:05,311 - Probe_Log - INFO -   Checked interface route to : 2a00:1450:4003:808::200e. Result: 2a00:1450:4003:808::200e from :: via fe80::1 dev wlan0 proto ra src 2001xxxxxxxxxxxxxxxxxxxxx:2006 metric 1024 hoplimit 64 pref medium
> 2021-03-26 20:52:05,312 - Probe_Log - INFO -   Correct interface being used for ipv6 tests.
> 2021-03-26 20:52:05,312 - Probe_Log - INFO -   Getting adapter IPv4 info: wlan0
> 2021-03-26 20:52:05,323 - Probe_Log - DEBUG - Interface config info: 3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>     inet 192.168.1.165/24 brd 192.168.1.255 scope global dynamic wlan0
>        valid_lft 3528sec preferred_lft 3528sec
> 
> 2021-03-26 20:52:05,324 - Probe_Log - DEBUG - IP Address = 192.168.1.165
> 2021-03-26 20:52:05,324 - Probe_Log - INFO -   [Check Interface Routes (IPv6)] Checking if we need to remove any interface routes...
> 2021-03-26 20:52:05,335 - Probe_Log - ERROR -   [Check Interface Routes (IPv6)] Issue looking up route (route cmd syntax?): Error: inet6 prefix is expected rather than "192.168.1.165".
>  (command used: /sbin/ip -6 route show to match 192.168.1.165 | grep '/')

Routing table:

> root@raspberrypiredewifi:/home/pi# ip -6 route
> ::1 dev lo proto kernel metric 256 pref medium
> 200xxxxxxxxxxxx00::/64 dev wlan0 proto kernel metric 256 expires 86380sec pref medium
> fe80::/64 dev ztukutsbw2 proto kernel metric 256 pref medium
> fe80::/64 dev wlan0 proto kernel metric 256 pref medium
> default via fe80::1 dev wlan0 proto ra metric 1024 expires 280sec hoplimit 64 pref medium
> 
> 
> root@raspberrypiredewifi:/home/piroot@raspberrypiredewifi:/home/pi# ip -4 route
> default via 192.168.1.1 dev wlan0
> 192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.165
> 192.168.192.0/24 dev ztukutsbw2 proto kernel scope link src 192.168.192.194
> root@raspberrypiredewifi:/home/pi#

**Comment by wifinigel** [comment]
Issue found in file /usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/networkconnectiontester.py

Fixed file pushed to dev repo.

Download new file as follows (SSH to RPi):

```
cd /usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/
# download fixed file
sudo curl https://raw.githubusercontent.com/wifinigel/wiperf_poller/dev/wiperf_poller/testers/networkconnectiontester.py --output networkconnectiontester.py
```
Retest and verify if default route issue now fixed. Thanks!

**Comment by lealog** [comment]
Fxed :)

Can be closed
