### ISSUE TITLE
typo: influx_2port

### ISSUE THREAD

**Issue by jyoung15** [wifinigel/wiperf_poller#26]
Hi,

There appears to be a typo here (`influx_2port` -> `influx2_port`):
https://github.com/wifinigel/wiperf_poller/blob/1725b81870fb43dd72e8f033663cb63727a2af6a/wiperf_poller/helpers/config.py#L110

This results in a traceback when attempting to set a non-default Influx2 port:

```python
  File "/usr/local/lib/python3.9/dist-packages/wiperf_poller/helpers/config.py", line 110, in read_local_config
    config_vars['data_port'] = config_vars['influx_2port']
KeyError: 'influx_2port'
```

The default config.ini uses `influx2_port`:
https://github.com/wifinigel/wiperf/blob/640a7a2c3c9427b8e014629e564bd75756a28357/config.default.ini#L89

**Comment by wifinigel** [comment]
Hi, thank you very much for posting this. @jyoung15 

I have posted a new version that should fix the issue for you.

Really appreciate your feedback on this.

Nigel 👍

**Comment by jyoung15** [comment]
Thank you @wifinigel for the quick response and resolution.  Looks good now.
